version: "3.8"

services:
  node-service:
    build: ./node-service
    ports:
      - "5000:5000"
    restart: always

  python-service:
    build: ./python-service
    ports:
      - "7000:7000"
    restart: always
